### ISSUE TITLE
Cross platform bootstrap?

### ISSUE THREAD

**Issue by Alicemargatroid** [mosra/magnum-bootstrap#7] opened 2016-05-26 22:41 UTC
Is there any procedure to get Magnum working on as many platforms as possible, as quickly as possible? I noticed it's possible to get Magnum to build many platforms via Jenkins; is there an established way to get a project _using Magnum_ to build similarly?

**Comment by mosra** [comment] 2016-05-27 07:32
Hi,

if you base your project on [Sdl2Application](http://mosra.cz/blog/magnum-doc/classMagnum_1_1Platform_1_1Sdl2Application.html) and [base](https://github.com/mosra/magnum-bootstrap/tree/base) bootstrap, you should be 90% there, as SDL2 covers all desktop platforms (OSX, Windows, Linux), iOS, Windows Phone/Store and web apps. (Android support is not done for `Sdl2Application` yet, but it is underway.) The actual C++ code doesn't need to be changed much -- in fact it is possible to have one codebase for everything, if you restrict yourselves to a subset of GL API that works on all platforms on your interest. The last 10% involves copying various platform-specific bits and pieces from other bootstrap projects ([base-ios](https://github.com/mosra/magnum-bootstrap/tree/base-ios), [base-android](https://github.com/mosra/magnum-bootstrap/tree/base-android), [base-winrt](https://github.com/mosra/magnum-bootstrap/tree/base-winrt), [base-emscripten](https://github.com/mosra/magnum-bootstrap/tree/base-emscripten) etc.) and then compile the project in a specific way for each platform, as described in the [README](https://github.com/mosra/magnum-bootstrap#contents-of-the-repository).

The reason why I did not do any "universal" bootstrap project is that there is simply too many platforms with too many platform-specific boilerplate files (for instance, imagine having to provide 20+ slightly different icon files to cover all possible mobile platforms by default -- that would be kinda painful) and not every project wants to cover all the platforms. For example, Google Chrome Native Client or Windows Phone with their 0.7% market share could be the ones of the least interest. There is also no "one-size-fits-all" way to have the platform-specific boilerplate autogenerated from user-provided information and assets -- that's out of the scope of the project, rather a task for some additional abstraction layer on top.

Hope this helps, please correct me if I misunderstood the question.

**Comment by Alicemargatroid** [comment] 2016-05-27 22:17
Jeez, Windows Phone was 3% last year. I wonder what happened.

Okay, so, let me summarize so I understand:
1. SDL2 covers everywhere I want but Android (but Android support will come eventually)
2. By carefully using, say, OpenGL ES 2.0 that is compatible with WebGL, I can make a cross platform project work.
3. I'd need to keep my source C++ independent from the various bootstrap bases
4. I'll need all of the bootstrap bases, as there is no "unified" one.
5. There's no easy way to make a unified one.

This is great information, and definitely thank you for clarifying things for me.
But let me ask a few new questions:

1. Does Android need GLUT then? Would working with some platforms as GLUT and others as SDL be terribly difficult? 

2. Do you have any instructions on getting Jenkins to build a bootstrap project, not just Magnum itself? I've followed some of the instructions for cross compiling, and set up Jenkins to compile Magnum on a number of platforms, but if I can get the bootstrap project to compile via Jenkins too, even if not every platform, that would make that last 10% well worth doing.

Thank you very much for your help!

**Comment by mosra** [comment] 2016-05-27 23:14
I'll try to explain a bit more:

> 1. SDL2 covers everywhere I want but Android (but Android support will come eventually)
>
> 1. Does Android need GLUT then? Would working with some platforms as GLUT and others as SDL be terribly difficult?

The thing is that I started the Android support before SDL2 officially supported it, so there was [AndroidApplication](http://mosra.cz/blog/magnum-doc/classMagnum_1_1Platform_1_1AndroidApplication.html) first. It should be roughly source-compatible with `Sdl2Application` so *in theory* the only place where things would differ are [two CMake lines](https://github.com/mosra/magnum-bootstrap/blob/1c5a93695397191613d88e26c8fdbb1d9aad6f0f/src/CMakeLists.txt#L3-L7) and [two includes](https://github.com/mosra/magnum-bootstrap/blob/1c5a93695397191613d88e26c8fdbb1d9aad6f0f/src/MyApplication.cpp#L2-L6). More info [in the docs](http://mosra.cz/blog/magnum-doc/portability.html#portability-applications). In reality `Sdl2Application` will always be much more featureful (because it's crazy easy to add new features using SDL2 and eternal pain to do it with the Android APIs) and you will miss those features in `AndroidApplication`.

> 2. By carefully using, say, OpenGL ES 2.0 that is compatible with WebGL, I can make a cross platform project work.

Yup. Or you can bite the bullet, drop GLES2 and jump to the shiny new GLES3 and WebGL 2. I didn't check lately what's the state of WebGL 2 in browsers, but the last time I tried (Dec 2015) it was working in both Firefox and Chrome, though under some off-by-default option. Check [list of supported WebGL extensions](http://mosra.cz/blog/magnum-doc/opengl-support.html#opengl-support-webgl20-extensions) and [required OpenGL versions for particular APIs](http://mosra.cz/blog/magnum-doc/opengl.html).

> 3. I'd need to keep my source C++ independent from the various bootstrap bases
> 4. I'll need all of the bootstrap bases, as there is no "unified" one.
> 5. There's no easy way to make a unified one.

The main difference among the bootstrap projects is only in the `CMakeLists.txt` file and various additional files, the C++ code stays the same in most cases. The examples repository has a `ports` branch where you can see some of the examples ported to various platforms. It's mainly about adding some `if()` statements to the `CMakeLists.txt` file and not much about changing the C++ code, as you can see [in the triangle example](https://github.com/mosra/magnum-examples/tree/ports/src/triangle) that is ported to desktop, iOS, NaCl, Android and Emscripten. *(Huh, now I realized that the `ports` branch is quite outdated, so take it with a grain of salt.)*

I'm not saying it's not easy, it's just ugly and confusing when combined all together, that's why it's not included in the (hopefully) self-documenting bootstrap projects. (Updated) excerpt from the triangle example `CMakeLists.txt` to show what I mean:

```cmake
find_package(Magnum REQUIRED Shaders)

if(CORRADE_TARGET_NACL)
    find_package(Magnum REQUIRED NaClApplication)
elseif(CORRADE_TARGET_ANDROID)
    find_package(Magnum REQUIRED AndroidApplication)
else()
    find_package(Magnum REQUIRED Sdl2Application)
endif()

# Executable on sane systems
if(NOT CORRADE_TARGET_ANDROID)
    add_executable(magnum-triangle TriangleExample.cpp)

# Dynamic library on Android
else()
    file(MAKE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/libs/${ANDROID_ABI}")
    set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/libs/${ANDROID_ABI}")
    add_library(magnum-triangle SHARED TriangleExample.cpp)
endif()

target_link_libraries(magnum-triangle
    Magnum::Application
    Magnum::Magnum
    Magnum::Shaders)

# iOS-specifics
if(CORRADE_TARGET_IOS)
    set_target_properties(magnum-triangle PROPERTIES
        MACOSX_BUNDLE ON
        MACOSX_BUNDLE_INFO_PLIST ${CMAKE_CURRENT_SOURCE_DIR}/MacOSXBundleInfo.plist.in
        XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED "YES")
endif()

# Installation for NaCl
if(CORRADE_TARGET_NACL)
    install(FILES triangle-nacl.html triangle-nacl.nmf DESTINATION ${CMAKE_INSTALL_PREFIX})
    install(TARGETS magnum-triangle DESTINATION ${CMAKE_INSTALL_PREFIX})

# Installation for Emscripten
elseif(CORRADE_TARGET_EMSCRIPTEN)
    install(FILES triangle-emscripten.html DESTINATION ${CMAKE_INSTALL_PREFIX})
    install(TARGETS magnum-triangle DESTINATION ${CMAKE_INSTALL_PREFIX})
    install(FILES ${CMAKE_CURRENT_BINARY_DIR}/magnum-triangle.js.mem DESTINATION ${CMAKE_INSTALL_PREFIX} OPTIONAL)

# Installation for desktop
elseif(NOT CORRADE_TARGET_IOS)
    install(TARGETS magnum-triangle DESTINATION ${MAGNUM_BINARY_INSTALL_DIR})
    install(FILES README.md DESTINATION ${MAGNUM_DATA_INSTALL_DIR}/examples RENAME README-triangle.md)
endif()
```

Jenkins: I would start by copy-pasting the compilation instructions [from README](https://github.com/mosra/magnum-bootstrap#base-application-with-port-to-emscripten-html5webgl). It's always create build dir, feed some parameters to CMake, compile, install/package. Combined compilation for desktop, Emscripten and Android on Linux could look like this:
```sh
# Pull the tooolchain submodule
git submodule init --update

# Desktop
mkdir build && cd build
cmake .. \
    -DCMAKE_INSTALL_PREFIX=~/deploy-desktop
cmake --build .
cmake --build . --target install
cd ..

# Emscripten
mkdir build-emscripten && cd build-emscripten
cmake .. \
    -DCMAKE_TOOLCHAIN_FILE="../toolchains/generic/Emscripten.cmake" \
    -DCMAKE_INSTALL_PREFIX=~/deploy-emscripten
cmake --build .
cmake --build . --target install
cd ..

# Android
android update project -p . -t "android-19"
mkdir build-android-arm && cd build-android-arm
cmake .. \
    -DCMAKE_TOOLCHAIN_FILE="../toolchains/generic/Android-ARM.cmake"
cmake --build .
ant debug
cp bin/NativeActivity-debug.apk ~/deploy-android/
cd ..
```

**Comment by chrisspaceape** [comment] 2016-05-28 22:25
Hi me again :)
I've built corrade and magnum using the cross compilation steps in your docs. They're now in my android sdk usr folder.
When I build and run the base-android bootstrap branch I get this from ant clean debug:
```
Buildfile: /Users/chrisjubb/dev/magnum-bootstrap/build.xml

-check-env:
 [checkenv] Android SDK Tools Revision 25.1.6
 [checkenv] Installed at /Users/chrisjubb/Library/Android/sdk

-setup:
     [echo] Project Name: NativeActivity
  [gettype] Project Type: Application

-pre-clean:

clean:
   [delete] Deleting directory /Users/chrisjubb/dev/magnum-bootstrap/bin
[getlibpath] Library dependencies:
[getlibpath] No Libraries
   [subant] No sub-builds to iterate on

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 25.1.6
 [checkenv] Installed at /Users/chrisjubb/Library/Android/sdk

-setup:
     [echo] Project Name: NativeActivity
  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 23.0.3
     [echo] Resolving Build Target for NativeActivity...
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: /Users/chrisjubb/dev/magnum-bootstrap/bin
    [mkdir] Created dir: /Users/chrisjubb/dev/magnum-bootstrap/bin/res
    [mkdir] Created dir: /Users/chrisjubb/dev/magnum-bootstrap/bin/rsObj
    [mkdir] Created dir: /Users/chrisjubb/dev/magnum-bootstrap/bin/rsLibs
     [echo] ----------
     [echo] Resolving Dependencies for NativeActivity...
[dependency] Ordered libraries:
[dependency] 
[dependency] ------------------
     [echo] ----------
     [echo] Building Libraries with 'debug'...
   [subant] No sub-builds to iterate on

-code-gen:
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] hasCode = false. Skipping aidl/renderscript/R.java

-pre-compile:

-compile:
     [echo] hasCode = false. Skipping...

-post-compile:

-obfuscate:

-dex:
     [echo] hasCode = false. Skipping...

-crunch:
   [crunch] Crunching PNG Files in source dir: /Users/chrisjubb/dev/magnum-bootstrap/res
   [crunch] To destination dir: /Users/chrisjubb/dev/magnum-bootstrap/bin/res
   [crunch] Crunched 0 PNG files to update cache

-package-resources:
     [aapt] Creating full resource package...

-package:
[apkbuilder] Current build type is different than previous build: forced apkbuilder run.
[apkbuilder] Creating NativeActivity-debug-unaligned.apk and signing it with a debug key...

-post-package:

-do-debug:
 [zipalign] Running zip align on final apk...
     [echo] Debug Package: /Users/chrisjubb/dev/magnum-bootstrap/bin/NativeActivity-debug.apk
[propertyfile] Creating new property file: /Users/chrisjubb/dev/magnum-bootstrap/bin/build.prop
[propertyfile] Updating property file: /Users/chrisjubb/dev/magnum-bootstrap/bin/build.prop
[propertyfile] Updating property file: /Users/chrisjubb/dev/magnum-bootstrap/bin/build.prop
[propertyfile] Updating property file: /Users/chrisjubb/dev/magnum-bootstrap/bin/build.prop

-post-build:

debug:

BUILD SUCCESSFUL
Total time: 3 seconds
```

And then when I run on device (the actual error):
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{cz.mosra.magnum.MyApplication/android.app.NativeActivity}: java.lang.IllegalArgumentException: Unable to load native library: /data/app/cz.mosra.magnum.MyApplication-2/lib/arm/libMyApplication.so
```


Any ideas? I've been struggling for ages now :/
I've setup the sdk correctly by the looks of it. I've tried lots of different combinations for the lib/ directory - eg. libs/   and then inside arm/   armeabi/

Hope you can help. Thanks

**Comment by mosra** [comment] 2016-05-30 00:17
Hi, sorry for no reply -- will get back to you soon once I fix the build issues I'm currently having.

**Comment by chrisspaceape** [comment] 2016-05-30 05:21
Ok no worries. Glad it's something you're experiencing too not just me.

**Comment by mosra** [comment] 2016-06-04 19:55
@chrisspaceape Sorry that it took so long -- managed to reproduce on my side and https://github.com/mosra/magnum/commit/60b6889ca634e583182e4881386c08761a2e4ca7 should fix it.

**Comment by chrisspaceape** [comment] 2016-06-04 21:15
Cheers will give that a go. Thanks.
On 4 Jun 2016 20:55, "Vladimír Vondruš" <notifications@github.com> wrote:

> @chrisspaceape <https://github.com/chrisspaceape> Sorry that it took so
> long -- managed to reproduce on my side and mosra/magnum@60b6889
> <https://github.com/mosra/magnum/commit/60b6889ca634e583182e4881386c08761a2e4ca7>
> should fix it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mosra/magnum-bootstrap/issues/7#issuecomment-223775004>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQmV2VE_FQ0QqB-Jqw-VR_9N28cGgrk7ks5qIdg5gaJpZM4IoBUD>
> .
>

-- 
 

-- 

Space Ape Games (UK) Limited is registered in England and Wales, 
No. 7956131. 
Registered office: Space Ape Games, First Floor, 100 New Oxford Street, 
London WC1A 1HB.

**Comment by chrisspaceape** [comment] 2016-06-08 16:39
Works perfectly! Thanks so much :)
Had my CMakeLists a bit odd too - statically linking in the TgaImporter now and placing the .so file in /libs/ like you do in the bootstrap project.

**Comment by Alicemargatroid** [comment] 2016-06-12 23:36
@mosra So, I've been piecing this together bit by bit.
I've got Corrade compiling on Linux, Android, MingW, and Emscripten, exactly according to the guide.
However, I encounter errors when attempting to make Magnum:

> 
>   Could NOT find Corrade (missing: CORRADE_INCLUDE_DIR
>   _CORRADE_CONFIGURE_FILE)
> Call Stack (most recent call first):
>   /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
>   modules/FindCorrade.cmake:237 (find_package_handle_standard_args)
>   CMakeLists.txt:41 (find_package)
> 

Happens on both Androids and Emscripten, where as I can't find a bootstrap branch for MingW or exact instructions on how to compile the base branch for it. Any help would be appreciated!

**Comment by mosra** [comment] 2016-06-13 13:36
Ah, sorry, forgot to document this -- seems to be some inconsistency with CMake which I was not able to pinpoint yet. The solution is to specify the directory where Corrade is installed in *both* `CMAKE_PREFIX_PATH` and `CMAKE_FIND_ROOT_PATH`. Will update the documentation accordingly.

In case of MinGW (you are compiling from Linux, I guess?) there was no code difference compared to the `base` branch of bootstrap repo, that's why there is no specific branch for it. Instructions tailored to ArchLinux (package names etc.) are here: http://mosra.cz/blog/magnum-doc/building.html#building-cross-win .. basically it's all about having the right packages and specifying proper toolchain file in `CMAKE_TOOLCHAIN_FILE`, no other difference. In case you are building with MinGW on Windows, then it should "just work" with no special CMake parameters providing you have MinGW `bin/` directory in `PATH`. Oh, and in case the documentation doesn't mention it, you need the MinGW-w64 fork, the original poorly maintained MinGW32 has severe issues regarding C++11 and is not supported anymore.

Um... and Emscripten currently doesn't fully compile on master branch of Magnum and I'm in progress of fixing all the issues (sorry), please try the work-in-progress `ci-updates` branch instead, it should mostly work. I will put the fixes back into master once they are complete.

**Comment by mosra** [comment] 2016-06-17 18:32
As of mosra/magnum@4bd958ab8cff936eb6862ee8b8f82367a934a351 Emscripten compiles on master with all tests green.

**Comment by Alicemargatroid** [comment] 2016-06-26 07:13
@mosra So, got Linux and MingW64 support working fully. Emscripten can find Corrade now. But I can't seem to find OpenGL ES when compiling Magnum under Emscripten:

    Could NOT find OpenGLES2 (missing: OPENGLES2_INCLUDE_DIR)

Any help appreciated!

**Comment by mosra** [comment] 2016-06-26 09:16
Hmm... not sure what could be the problem. Can you check that the CMake variable `EMSCRIPTEN_PREFIX` is correct in the `toolchains/Emscripten.cmake` file so `${EMSCRIPTEN_PREFIX}/system/include/GLES2` points to an existing directory?

This is being tested on the Travis CI, so maybe you can have a look [at the relevant output there](https://travis-ci.org/mosra/magnum/jobs/139251260#L440-L459) and compare with what you have.

In any case, if everything else fails and all hope is lost, you can always force the location explicitly by passing `-DOPENGLES2_INCLUDE_DIR=<your-emscripten-prefix>/system/include` to CMake.

**Comment by Alicemargatroid** [comment] 2016-06-26 21:53
@mosra Got it working for Emscripten; the issue was probably platform specific. I'm on Ubuntu 16.06, `EMSCRIPTEN_PREFIX` was pointing at `/usr/bin` needed to point at `/usr/share/emscripten`. My bad, and thank you for pointing that out.

Now, last platform left is Android; it appears it cannot find SDL2. I know `SDL2_APPLICATION` is not currently supported for Android, but do you have any tips on cross compiling SDL2 so I can try using it?

**Comment by mosra** [comment] 2016-06-26 22:58
Yes, there was some Android README somewhere: https://github.com/spurious/SDL-mirror/blob/master/docs/README-android.md

I have this on my TODO list, but am currently so overwhelmed with work (three weeks long crunch and still no light at the end of the tunnel) so I won't be able to do anything about that anytime soon... If you make any progress with this, please let me know :)

**Comment by Alicemargatroid** [comment] 2016-06-26 23:09
@mosra I will, don't worry. Thank you for all the help; I can definitely proceed with just Linux, Windows, and WebGL working, so don't worry about me. I'll report back if I figure out Android.

**Comment by mosra** [comment] 2016-08-16 14:01
Closing as resolved. Making SDL2 working on Android is on my private TODO list.

**Closed by mosra** 2016-08-16 14:01 UTC
